export { default as LandingPage } from "./LandingPage/LandingPage";
export { default as SignIn } from "./SignIn/SignIn";
export { default as Register } from "./Register/Register";
export { default as HomePage } from "./HomePage/HomePage";
export { default as ElectionsPage } from "./ElectionsPage/ElectionsPage";
export { default as ResultsPage } from "./ResultsPage/ResultsPage";
export { default as CreatePoll } from "./CreatePoll/CreatePoll";
export { default as PollPage } from "./PollPage/PollPage";
export { default as ResultPage } from "./ResultPage/ResultPage";
